backend:
  name: github
  repo: nafergo
  base_url: /webtest

media_folder: "static/images/uploads"

collections:
  - name: "journal"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string", required: false}
